# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_users',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_users',
            field=models.ManyToManyField(related_name='trip_user', to='belt.User'),
        ),
    ]
